// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using calledudeBot.Database;

namespace calledudeBotCore.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20200924175629_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("calledudeBot.Database.UserActivityEntity", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastJoinDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TimesSeen")
                        .HasColumnType("INTEGER");

                    b.HasKey("Username");

                    b.ToTable("UserActivities");
                });
#pragma warning restore 612, 618
        }
    }
}
