// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace calledudeBot.Database.Compiled
{
    public partial class DatabaseContextModel
    {
        partial void Initialize()
        {
            var userActivity = UserActivityEntityType.Create(this);
            var userSession = UserSessionEntityType.Create(this);

            UserActivityEntityType.CreateAnnotations(userActivity);
            UserSessionEntityType.CreateAnnotations(userSession);

            AddAnnotation("ProductVersion", "7.0.2");
        }
    }
}
